export const OPPORTUNITIES_MIN_PAGE = 1
export const OPPORTUNITIES_DEFAULT_PAGE = 1

export const OPPORTUNITIES_MIN_LIMIT = 1
export const OPPORTUNITIES_MAX_LIMIT = 1000
export const OPPORTUNITIES_DEFAULT_LIMIT = 200

export const OPPORTUNITIES_BAYES_PRIOR_WEIGHT = 5000
export const OPPORTUNITIES_USERS_P95 = 0.95
export const OPPORTUNITIES_VOTES_P95 = 0.95
export const OPPORTUNITIES_COMPETITION_P95 = 0.95
export const OPPORTUNITIES_GAP_CAP_P90 = 0.9

export const OPPORTUNITIES_SCORE_SCALE = 100
export const OPPORTUNITIES_SCORE_DEMAND_WEIGHT = 0.45
export const OPPORTUNITIES_SCORE_GAP_WEIGHT = 0.35
export const OPPORTUNITIES_SCORE_INVERSE_COMPETITION_WEIGHT = 0.2
